CREATE TABLE "wallets" (
  "id" int,
  "wallet_address" varchar UNIQUE,
  "created_block" varchar,
  "created at" varchar,
  PRIMARY KEY ("id", "wallet_address")
);

CREATE TABLE "transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "wallet_address" varchar,
  "chain" varchar,
  "chain_id" int,
  "txn_hash" varchar,
  "from_add" varchar,
  "to_add" varchar
);

ALTER TABLE "transactions" ADD FOREIGN KEY ("wallet_address") REFERENCES "wallets" ("wallet_address");
