CREATE TABLE "wallets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "wallet_address" varchar UNIQUE NOT NULL,
  "created_block" varchar,
  "created_at" timestamp DEFAULT (now())  NOT NULL,
  PRIMARY KEY ("id", "wallet_address")
);

CREATE TABLE "transactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "wallet_address" varchar NOT NULL,
  "chain" varchar NOT NULL,
  "chain_id" int NOT NULL,
  "txn_hash" varchar UNIQUE NOT NULL,
  "from_add" varchar NOT NULL,
  "to_add" varchar NOT NULL
);

CREATE TABLE "blocks" (
  "block_number" int UNIQUE NOT NULL,
  "processed" bool NOT NULL
);

ALTER TABLE "transactions" ADD FOREIGN KEY ("wallet_address") REFERENCES "wallets" ("wallet_address");
