// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: blocks.sql

package db

import (
	"context"
)

const addBlock = `-- name: AddBlock :one
INSERT INTO blocks (
    block_number,
    processed,
    chain_id
) VALUES ($1, $2, $3) RETURNING block_number
`

type AddBlockParams struct {
	BlockNumber int32 `json:"block_number"`
	Processed   bool  `json:"processed"`
	ChainID     int32 `json:"chain_id"`
}

func (q *Queries) AddBlock(ctx context.Context, arg AddBlockParams) (int32, error) {
	row := q.queryRow(ctx, q.addBlockStmt, addBlock, arg.BlockNumber, arg.Processed, arg.ChainID)
	var block_number int32
	err := row.Scan(&block_number)
	return block_number, err
}

const getAllBlock = `-- name: GetAllBlock :many
SELECT block_number FROM blocks
WHERE chain_id = $1
ORDER BY block_number ASC
`

func (q *Queries) GetAllBlock(ctx context.Context, chainID int32) ([]int32, error) {
	rows, err := q.query(ctx, q.getAllBlockStmt, getAllBlock, chainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var block_number int32
		if err := rows.Scan(&block_number); err != nil {
			return nil, err
		}
		items = append(items, block_number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotProcessBlock = `-- name: GetNotProcessBlock :many
SELECT block_number, processed, chain_id FROM blocks
WHERE processed = $1 AND chain_id = $2
ORDER BY block_number ASC
`

type GetNotProcessBlockParams struct {
	Processed bool  `json:"processed"`
	ChainID   int32 `json:"chain_id"`
}

func (q *Queries) GetNotProcessBlock(ctx context.Context, arg GetNotProcessBlockParams) ([]Blocks, error) {
	rows, err := q.query(ctx, q.getNotProcessBlockStmt, getNotProcessBlock, arg.Processed, arg.ChainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blocks
	for rows.Next() {
		var i Blocks
		if err := rows.Scan(&i.BlockNumber, &i.Processed, &i.ChainID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOneBlock = `-- name: GetOneBlock :one
SELECT block_number FROM blocks
WHERE block_number = $1 AND chain_id = $2
ORDER BY block_number ASC
LIMIT 1
`

type GetOneBlockParams struct {
	BlockNumber int32 `json:"block_number"`
	ChainID     int32 `json:"chain_id"`
}

func (q *Queries) GetOneBlock(ctx context.Context, arg GetOneBlockParams) (int32, error) {
	row := q.queryRow(ctx, q.getOneBlockStmt, getOneBlock, arg.BlockNumber, arg.ChainID)
	var block_number int32
	err := row.Scan(&block_number)
	return block_number, err
}

const updateBlockProcess = `-- name: UpdateBlockProcess :one
UPDATE blocks
SET 
    processed = $3
WHERE block_number = $1 AND chain_id = $2 RETURNING block_number, processed, chain_id
`

type UpdateBlockProcessParams struct {
	BlockNumber int32 `json:"block_number"`
	ChainID     int32 `json:"chain_id"`
	Processed   bool  `json:"processed"`
}

func (q *Queries) UpdateBlockProcess(ctx context.Context, arg UpdateBlockProcessParams) (Blocks, error) {
	row := q.queryRow(ctx, q.updateBlockProcessStmt, updateBlockProcess, arg.BlockNumber, arg.ChainID, arg.Processed)
	var i Blocks
	err := row.Scan(&i.BlockNumber, &i.Processed, &i.ChainID)
	return i, err
}
