// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"
)

type Blocks struct {
	BlockNumber int32 `json:"block_number"`
	Processed   bool  `json:"processed"`
}

type Transactions struct {
	ID            int32  `json:"id"`
	WalletAddress string `json:"wallet_address"`
	Chain         string `json:"chain"`
	ChainID       int32  `json:"chain_id"`
	TxnHash       string `json:"txn_hash"`
	FromAdd       string `json:"from_add"`
	ToAdd         string `json:"to_add"`
}

type Wallets struct {
	ID            int32          `json:"id"`
	WalletAddress string         `json:"wallet_address"`
	CreatedBlock  sql.NullString `json:"created_block"`
	CreatedAt     time.Time      `json:"created_at"`
}
